// ==UserScript==
// @name         回到真正顶部（通用·长对话/Agent 可用）
// @namespace    scroll-to-real-top
// @version      1.0.0
// @description  通用「回到真正顶部」：定位当前页面真正的滚动容器，反复把 scrollTop 归零并连续确认，解决 Home 键/一键到顶在虚拟长列表里到不了真实顶部的问题。所有网站可用，支持快捷键 Alt+T，并向其它脚本暴露 window.goToRealTop()
// @match        *://*/*
// @grant        none
// @run-at       document-idle
// @author       WorkBuddy · 小台 (workspace-builder)
// ==/UserScript==

// Generated by WorkBuddy · 小台 (workspace-builder)

(function () {
    'use strict';

    if (window.top !== window.self) return;

    const VERSION = '1.0.0';

    // 归零后连续确认次数（每轮间隔 CONFIRM_WAIT）
    const TOP_CONFIRM_TIMES = 4;

    const CONFIRM_WAIT = 500;

    // 外层重试轮数
    const MAX_ROUNDS = 10;

    const sleep = ms =>
        new Promise(r => setTimeout(r, ms));

    // =========================================================
    // 通用滚动容器探测
    //
    // 取「视口中心落在其中」且「可滚动距离最大」的容器。
    // 找不到就退回整页滚动 document.scrollingElement。
    // =========================================================

    function findGenericScroller() {

        const cx = window.innerWidth / 2;

        const cy = window.innerHeight / 2;

        let best = null;

        let bestRange = 0;

        for (
            const el of
            document.querySelectorAll('*')
        ) {

            const s = getComputedStyle(el);

            if (
                !/auto|scroll|overlay/
                    .test(s.overflowY)
            ) {
                continue;
            }

            const range =
                el.scrollHeight -
                el.clientHeight;

            if (range <= 50) continue;

            const r =
                el.getBoundingClientRect();

            if (
                r.width < 200 ||
                r.height < 200
            ) {
                continue;
            }

            if (
                cx < r.left ||
                cx > r.right ||
                cy < r.top ||
                cy > r.bottom
            ) {
                continue;
            }

            if (range > bestRange) {

                bestRange = range;

                best = el;
            }
        }

        if (best) return best;

        const de = document.scrollingElement;

        return de || document.documentElement;
    }

    // =========================================================
    // 到真正顶部
    //
    // 不是"看起来到了顶部"，而是 scrollTop = 0 且连续稳定确认。
    // 虚拟长列表归零后常会二次布局把位置顶回去，
    // 所以必须反复归零 + 连续确认。
    // =========================================================

    async function goToRealTop(input, onProgress) {

        const scroller =
            input || findGenericScroller();

        if (!scroller) {

            if (onProgress) {
                onProgress(
                    '没有找到可滚动容器'
                );
            }

            return false;
        }

        for (
            let round = 1;
            round <= MAX_ROUNDS;
            round++
        ) {

            scroller.scrollTop = 0;

            await sleep(60);

            if (scroller.scrollTop <= 1) {

                let stable = 0;

                for (
                    let i = 0;
                    i < TOP_CONFIRM_TIMES;
                    i++
                ) {

                    scroller.scrollTop = 0;

                    await sleep(CONFIRM_WAIT);

                    if (
                        scroller.scrollTop <= 1
                    ) {

                        stable++;

                    } else {

                        stable = 0;
                    }

                    if (onProgress) {

                        onProgress(
                            `确认中 ${stable}/${TOP_CONFIRM_TIMES}`
                        );
                    }
                }

                if (
                    stable >=
                    TOP_CONFIRM_TIMES
                ) {

                    if (onProgress) {
                        onProgress(
                            '已到达真正顶部'
                        );
                    }

                    return true;
                }
            }

            if (onProgress) {

                onProgress(
                    `第 ${round} 轮未稳住，重试…`
                );
            }

            await sleep(120);
        }

        if (onProgress) {

            onProgress(
                '未能确认到达真正顶部'
            );
        }

        return scroller.scrollTop <= 2;
    }

    // =========================================================
    // 给其它脚本 / agent 用
    //
    //   await window.goToRealTop()
    //   await window.goToRealTop(document.querySelector('#list'))
    //   await window.goToRealTop(null, msg => console.log(msg))
    // =========================================================

    window.goToRealTop = goToRealTop;

    // =========================================================
    // UI：左下角小圆钮 + Alt+T
    // =========================================================

    let btn = null;

    let tip = null;

    let busy = false;

    function showTip(text, ok) {

        if (!tip) return;

        tip.textContent = text;

        tip.style.display = 'block';

        tip.style.background =
            ok === undefined
                ? 'rgba(20,20,20,.88)'
                : ok
                    ? 'rgba(16,163,127,.94)'
                    : 'rgba(200,60,60,.92)';

        clearTimeout(showTip._t);

        showTip._t = setTimeout(
            () => {
                tip.style.display = 'none';
            },
            1600
        );
    }

    function createUI() {

        if (
            document.querySelector(
                '#gtt-root'
            )
        ) {
            return;
        }

        const style =
            document.createElement('style');

        style.textContent = `
            #gtt-root {
                position: fixed;
                left: 16px;
                bottom: 16px;
                z-index: 2147483646;
                font-family: -apple-system,
                    BlinkMacSystemFont,
                    "Segoe UI",
                    Roboto, Helvetica, Arial,
                    sans-serif;
            }

            #gtt-btn {
                width: 34px;
                height: 34px;
                border-radius: 50%;
                border: 1px solid rgba(127,127,127,.28);
                background: rgba(255,255,255,.9);
                color: #333;
                box-shadow: 0 2px 10px rgba(0,0,0,.16);
                cursor: pointer;
                font-size: 15px;
                line-height: 1;
                display: flex;
                align-items: center;
                justify-content: center;
                opacity: .35;
                transition: opacity .15s;
                user-select: none;
            }

            #gtt-btn:hover {
                opacity: 1;
            }

            #gtt-btn[data-busy="1"] {
                opacity: 1;
                cursor: progress;
            }

            #gtt-tip {
                position: absolute;
                left: 0;
                bottom: 42px;
                padding: 5px 9px;
                border-radius: 7px;
                background: rgba(20,20,20,.88);
                color: #fff;
                font-size: 11.5px;
                white-space: nowrap;
                display: none;
            }

            @media (prefers-color-scheme: dark) {
                #gtt-btn {
                    background: rgba(45,46,48,.92);
                    color: #eee;
                }
            }
        `;

        document.head.appendChild(style);

        const root =
            document.createElement('div');

        root.id = 'gtt-root';

        root.innerHTML = `
            <div id="gtt-tip"></div>
            <button id="gtt-btn" title="回到真正顶部（Alt+T）">↑</button>
        `;

        document.body.appendChild(root);

        btn =
            root.querySelector('#gtt-btn');

        tip =
            root.querySelector('#gtt-tip');

        btn.addEventListener(
            'click',
            () => {

                // 刚才是拖动，不是点击
                if (moved) {

                    moved = false;

                    return;
                }

                run();
            }
        );

        // 允许拖动到顺手的位置
        let dragging = false;

        let moved = false;

        let sx = 0;

        let sy = 0;

        let ox = 0;

        let oy = 0;

        btn.addEventListener(
            'mousedown',
            e => {

                dragging = true;

                moved = false;

                sx = e.clientX;

                sy = e.clientY;

                const r =
                    root.getBoundingClientRect();

                ox = r.left;

                oy = r.top;

                e.preventDefault();
            }
        );

        window.addEventListener(
            'mousemove',
            e => {

                if (!dragging) return;

                const dx =
                    e.clientX - sx;

                const dy =
                    e.clientY - sy;

                if (
                    Math.abs(dx) > 3 ||
                    Math.abs(dy) > 3
                ) {
                    moved = true;
                }

                root.style.left =
                    Math.max(
                        0,
                        Math.min(
                            window.innerWidth - 40,
                            ox + dx
                        )
                    ) + 'px';

                root.style.bottom =
                    'auto';

                root.style.top =
                    Math.max(
                        0,
                        Math.min(
                            window.innerHeight - 40,
                            oy + dy
                        )
                    ) + 'px';
            }
        );

        window.addEventListener(
            'mouseup',
            () => {

                dragging = false;
            }
        );
    }

    async function run() {

        if (busy) return;

        busy = true;

        if (btn) {

            btn.dataset.busy = '1';

            btn.textContent = '…';
        }

        let ok = false;

        try {

            ok =
                await goToRealTop(
                    null,
                    msg => showTip(msg)
                );

        } finally {

            busy = false;

            if (btn) {

                btn.dataset.busy = '0';

                btn.textContent = '↑';
            }

            showTip(
                ok
                    ? '已到达真正顶部 ✓'
                    : '未能确认，可能仍在加载',
                ok
            );
        }
    }

    // Alt + T
    window.addEventListener(
        'keydown',
        e => {

            if (
                e.altKey &&
                !e.ctrlKey &&
                !e.metaKey &&
                (
                    e.code === 'KeyT' ||
                    String(e.key)
                        .toLowerCase() === 't'
                )
            ) {

                e.preventDefault();

                run();
            }
        },
        true
    );

    function init() {

        createUI();

        console.log(
            `[回到真正顶部 ${VERSION}] 已启动 · Alt+T`
        );
    }

    if (document.body) {

        init();

    } else {

        document.addEventListener(
            'DOMContentLoaded',
            init
        );
    }

})();
